### ISSUE TITLE
Inconsistent licencing information

### ISSUE THREAD

**Issue by ed588** [oliverh57/Vision#11]
In the licence file, LICENCE, it says that this is MIT licenced by "Oliver Hynds".

However in the footer of the website it says "Copyright Oliver Hynds, Robert Bradshaw, Ben Griffiths and W3Schools". 

This is:

1. inconsistent as the list of creators differs in different locations
2. misleading as the footer of the website just says "copyright" without indicating how the system is licenced.
3. wrong because it attributes w3schools as a creator of the website. This is not the case. If you want to credit w3schools for creating w3.css, you should not do this in with "copyright" as this means w3schools could claim copyright on this system if they so desired

**Comment by oliverh57** [comment]
The W3 school's issue was fixed a while ago **but**; I have updated the footer to read *Made by...*. This was a relic of the site existing online before publishing it to GitHub.
