### ISSUE TITLE
even worse versioning system

### ISSUE THREAD

**Issue by ed588** [oliverh57/Vision#14]
since my last issue, #9, your versioning system has got even worse.

In case you didn't know, the major number is only supposed to change if this version makes something **backwards-incompatible**. Not when you make a big change. That's for the middle number.

Additionally, you can't just go around changing the version numbers of previous versions willy-nilly. What is this, 1984?

**Comment by oliverh57** [comment]
The versions were no longer backwards compatible. I changed them because if issue #9
